resultdir: analysis_rdna2

# INPUTS
# gtf-files with tx
gtf:
  files: files.rdna2.txt
  # for each tx in a gtf file extract TSS and then extract this many nt
  # upstream and dnstream. This will be the region to look for gRNAs.
  upstream: 250
  dnstream: 250

# GENOME
ref:
  # fasta-file
  genome: GRCm38.primary_assembly.genome.fa
  # the genome version
  # currently supported hg38, hg19, mm10, mm9
  version: mm10

crispr:
  # test this many top gRNAs for off targets
  # the more the longer it will run
  max_num_test: 20
  # will not consider any gRNA with a lower efficacy
  min_efficacy: 0
  # number allowed missmatches for offtarget analysis
  num_mm: 0
  # Number of final selected "best" gRNAs per tx
  num_select: 5
  # offtarget scoring methog, Hsu-Zhang or CFDscore
  scoring_method: Hsu-Zhang
