$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  resultdir:
    type: string

  gtf:
    type: object
    properties:
      files:
        type: string
      upstream:
        type: integer
      dnstream:
        type: integer
    required:
      - files
      - upstream
      - dnstream

  ref:
    type: object
    properties:
      genome:
        type: string
      version:
        type: string
    #        oneOf:
    #          - hg38
    #          - hg19
    #          - mm10
    #          - mm9
    required:
      - genome
      - version

  crispr:
    type: object
    properties:
      same_strand:
        type: boolean
      max_num_test:
        type: integer
      min_efficacy:
        type: number
      num_mm:
        type: integer
      num_select:
        type: integer
      scoring_method:
        type: string
    #        oneOf:
    #          - Hsu-Zhang
    #          - CFDscore
    required:
      - same_strand
      - max_num_test
      - min_efficacy
      - num_mm
      - num_select
      - scoring_method

required:
  - resultdir
  - gtf
  - ref
  - crispr
